DROP TABLE IF EXISTS usuario_livro;
DROP TABLE IF EXISTS livro;
DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL
);

CREATE TABLE livro (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    ano_publicacao INT NOT NULL,
    genero VARCHAR(100) NOT NULL,
    quantidade INT NOT NULL CHECK (quantidade >= 0),
    autor VARCHAR(100) NOT NULL
);

CREATE TABLE usuario_livro (
    usuario_id INT NOT NULL,
    livro_id INT NOT NULL,
    data_emprestimo DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (usuario_id, livro_id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    FOREIGN KEY (livro_id) REFERENCES livro(id)
);
