DROP TABLE IF EXISTS livro;
DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL
);

CREATE TABLE livro (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    ano_publicacao INT NOT NULL,
    genero VARCHAR(100) NOT NULL,
    quantidade INT NOT NULL CHECK (quantidade >= 0),
    autor VARCHAR(100) NOT NULL,
    usuario_id INT,
    CONSTRAINT fk_livro_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);
